# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pR-gH1JqidD2RB1KU7JwV2uf5hIteDvE
"""

from OpenGL.GL import *
from OpenGL.GLUT import *
from OpenGL.GLU import *
import random
import time


class MPL_caller:
    def find_zone(self, x1, y1, x2, y2):
        dx = x2 - x1
        dy = y2 - y1
        if abs(dx) >= abs(dy):
            if dx > 0 and dy > 0:
                return 0
            elif dx < 0 and dy > 0:
                return 3
            elif dx < 0 and dy < 0:
                return 4
            else:
                return 7
        else:
            if dx > 0 and dy > 0:
                return 1
            elif dx < 0 and dy > 0:
                return 2
            elif dx < 0 and dy < 0:
                return 5
            else:
                return 6

    def c_nvzone0(self, x, y, z1):
        axis_def = [( x, y), ( y, x),( y,-x),  (-x, y),  (-x,-y),  (-y, -x), (-y, x),  ( x, -y)  ]
        return axis_def[z1]

    def f_z10(self, x, y, z1):
        axis_def = [( x, y), ( y, x), (-y, x),  (-x, y),  (-x,-y),  (-y,-x), ( y,-x), ( x, -y) ]
        return axis_def[z1]

    def mpl_on_z10(self, x1, y1, x2, y2):
        x1, y1, x2, y2 = int(round(x1)), int(round(y1)), int(round(x2)), int(round(y2))
        dx = x2 - x1
        dy = y2 - y1
        d = 2 * dy - dx
        dirEa = 2 * dy
        dirNEa = 2 * (dy - dx)
        y = y1
        points = []
        for x in range(x1, x2 + 1):
            points.append((x, y))
            if d > 0:
                d += dirNEa
                y += 1
            else:
                d += dirEa
        return points

    def draw_line(self, x1, y1, x2, y2):
        zone = self.find_zone(x1, y1, x2, y2)
        zx1, zy1 = self.c_nvzone0(x1, y1, zone)
        zx2, zy2 = self.c_nvzone0(x2, y2, zone)
        zone0_pts = self.mpl_on_z10(zx1, zy1, zx2, zy2)
        temp = []
        for a, b in zone0_pts:
            temp.append(self.f_z10(a, b, zone))
        return temp


class Diamond:
    ini_sz= 25
    def __init__(self, x, y, sz=ini_sz):
        self.x = x
        self.y = y
        self.sz = sz
        self.col = (random.random(), random.random(), random.random())

    def fall(self, dy):
        self.y -= dy

    def g_function(self):
        return (self.x, self.y, self.sz, self.sz)


class DiamondCatcherGame:
    def __init__(self):
        self.w_th = 800
        self.he_t = 800
        self.cat_x = self.w_th // 2
        self.cat_y = 50
        self.cat_wdth = 100
        self.cat_h_ght = 25
        self.dia_speed = 1.3
        self.p_score = 0
        self.game_over = 0
        self.pause_checker = 0
        self.cheater = 0
        self.diamond = self.spawn_diamond()
        self.mpl = MPL_caller()
        self.last_time = time.time()
        self.button_areas = { "res1": (52, self.he_t-56, 35, 35),"pau1": (self.w_th//2-20, self.he_t-56, 35, 35), "qui1": (self.w_th-90, self.he_t-56, 35, 35) }

    def spawn_diamond(self):
        x = random.randint(20, self.w_th - 20)
        y = self.he_t - 65
        return Diamond(x, y, Diamond.ini_sz )

    def move_catcher(self, dx):
        if self.game_over or self.pause_checker:
            return

        self.cat_x += dx

        if self.cat_x < 0:
            self.cat_x = 0
        elif self.cat_x > self.w_th - self.cat_wdth:
            self.cat_x = self.w_th - self.cat_wdth

    def toggle_pause(self):
        self.pause_checker = 1 - self.pause_checker
        if not self.pause_checker:
          self.last_time = time.time()

    def toggle_cheat(self):
        self.cheater = 1 - self.cheater

    def reset_game(self):
        self.p_score = 0
        self.game_over = 0
        self.dia_speed = 1.3
        self.cat_x = self.w_th // 2
        self.diamond = self.spawn_diamond()
        self.last_time = time.time()
        print("Starting Over")

    def check_collu(self):
        dx, dy, ds, _ = self.diamond.g_function()
        cx, cy = self.cat_x, self.cat_y
        cw, ch = self.cat_wdth, self.cat_h_ght
        half = ds / 2
        left   = dx - half
        right  = dx + half
        top    = dy + half
        bottom = dy - half
        c_left   = cx
        c_right  = cx + cw
        c_top    = cy + ch
        c_bottom = cy
        if (left < c_right and right > c_left and bottom < c_top and top > c_bottom):
            return 1
        else:
            return 0

    def update_withcheater(self):
        if self.pause_checker or self.game_over:
            return
        current_time = time.time()
        del_time = current_time - self.last_time
        self.last_time = current_time
        dy = self.dia_speed * del_time * 60


        if self.cheater:
            self.cat_x = int(self.diamond.x + self.diamond.sz/2 - self.cat_wdth/2)
            self.cat_x = max(0, min(self.w_th - self.cat_wdth, self.cat_x))
        self.diamond.fall(dy)


        if self.check_collu():
            self.p_score += 1
            print("Score:", self.p_score)
            self.dia_speed += 0.2
            self.diamond = self.spawn_diamond()
        elif self.diamond.y <= 0 and not self.game_over:
            self.game_over = 1
            print("Game Over! Final Score:", self.p_score)

    def draw_shape_struc(self, points, col=(1,1,1)):
        glColor3f(*col)
        for i in range(len(points)):
            ax1, ay1 = points[i]
            ax2, ay2 = points[(i+1)%len(points)]
            pts = self.mpl.draw_line(ax1, ay1, ax2, ay2)
            for px, py in pts:
                glVertex2f(px, py)

    def draw_catcher(self):
        if self.game_over:
            col = (1, 0, 0)
        else:
            col = (1, 1, 1)

        x = self.cat_x
        y = self.cat_y
        w = self.cat_wdth
        h = self.cat_h_ght
        add = 12
        points = [(x+add,y),(x, y + h), (x + w,  y + h), (x + w -add, y),(x + add,y), (x+w-add,y)]
        self.draw_shape_struc(points, col)

    def draw_diamond(self, diamond):
        cx, cy, s = diamond.x, diamond.y, diamond.sz
        points = [(cx, cy + s//2),(cx + s//2, cy), (cx, cy - s//2),(cx - s//2, cy)]
        self.draw_shape_struc(points, col=diamond.col)

    def draw_buttons(self):
        re1x, re1y, re1w, re1h = self.button_areas["res1"]
        pa1x, pa1y, pa1w, pa1h = self.button_areas["pau1"]
        q1x, q1y, q1w, q1h = self.button_areas["qui1"]
        points=[(re1x,(re1y+re1y+re1h)/2),(re1x+re1w,re1y),(re1x+re1w,re1y+re1w) ]

        self.draw_shape_struc(points,col=(0.31,0.4,0.5))


        if not self.pause_checker:
            points = [(pa1x,pa1y),(pa1x,pa1y+pa1h)]
            self.draw_shape_struc(points)
            points = [(pa1x+pa1w,pa1y),(pa1x+pa1w,pa1y+pa1h)]
            self.draw_shape_struc(points)
        else:
            points = [(pa1x+pa1w, (pa1y+(pa1y+pa1h))/2), (pa1x, pa1y+pa1h),(pa1x, pa1y)]
            self.draw_shape_struc(points)


        points = [(q1x,q1y),(q1x ,q1y+q1h),(q1x+q1w, q1y),(q1x+q1w,q1y+q1h)]

        self.draw_shape_struc(points,col=(1,0,0))

    def render(self):
        glClear(GL_COLOR_BUFFER_BIT)
        glBegin(GL_POINTS)
        self.draw_catcher()
        self.draw_diamond(self.diamond)
        self.draw_buttons()
        glEnd()
        glutSwapBuffers()

    def key_pressed(self, key, x, y):
        if key == b'c':
            self.toggle_cheat()


    def special_pressed(self, key, x, y):
        if key == GLUT_KEY_LEFT:
            self.move_catcher(-12)
        elif key == GLUT_KEY_RIGHT:
            self.move_catcher(12)

    def quit_game(self):
        print(f"Goodbye! Last Score: {self.p_score}")
        glutLeaveMainLoop()

    def mouse_click(self, button, state, mx, my):
        if state != GLUT_DOWN:
            return
        my = self.he_t - my
        dic_1 = {"res1": self.reset_game, "pau1": self.toggle_pause, "qui1": self.quit_game }

        for key1, (bx, by, bw, bh) in self.button_areas.items():
            if bx <= mx <= bx + bw and by <= my <= by + bh:
                func1 = dic_1.get(key1)
                if func1:
                    func1()
                break



game = DiamondCatcherGame()

def run():
    game.update_withcheater()
    game.render()

def keyboard(key, x, y):
    game.key_pressed(key, x, y)

def special(key, x, y):
    game.special_pressed(key, x, y)

def mouse(button, state, x, y):
    game.mouse_click(button, state, x, y)


glutInit()
glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA)
glutInitWindowSize(game.w_th, game.he_t)
glutCreateWindow(b"Assign2 Dia Catcher")
glutDisplayFunc(run)
glutKeyboardFunc(keyboard)
glutSpecialFunc(special)
glutMouseFunc(mouse)
glutIdleFunc(run)
glOrtho(0, game.w_th, 0, game.he_t, 0, 1)
glutMainLoop()

# Python program to explain time.time() method

# importing time module
import time

# Get the epoch
obj = time.gmtime(0)
epoch = time.asctime(obj)
print("epoch is:", epoch)

# Get the time in seconds
# since the epoch
time_sec = time.time()

# Print the time
print("Time in seconds since the epoch:", time_sec)

