# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPfe3GU2iRHZucCqj9eucyKPSpOt0BQ5
"""

#Task 1
from OpenGL.GL import *
from OpenGL.GLUT import *
from OpenGL.GLU import *
import random


class House_with_rain:
    def __init__(self, w=500, h=500):
        self.width = w
        self.height = h
        self.drops = []
        self.initial_ang = 0.0
        self.initialbgcol = 0.0
        self.condtional_check = 0
        self.trans_speed = 0.004

    def trianstruct(self, x_p, y_p, w_p, h_p):
        glBegin(GL_TRIANGLES)
        glVertex2d(x_p, y_p)
        glVertex2d(x_p + w_p, y_p)
        glVertex2d(x_p + (w_p / 2), y_p + h_p)
        glEnd()

    def draw_background(self):
        glColor3f(self.initialbgcol , self.initialbgcol , self.initialbgcol )
        glBegin(GL_TRIANGLES)
        glVertex2d(0, 0)
        glVertex2d(self.width, 0)
        glVertex2d(self.width, self.height)
        glVertex2d(0, 0)
        glVertex2d(0, self.height)
        glVertex2d(self.width, self.height)
        glEnd()

    def draw_ground(self):
        glColor3f(0.36, 0.20, 0.09)
        gd_top = 208
        gd_bottom = 0
        lef_x = 0
        rig_x = self.width
        glBegin(GL_TRIANGLES)
        glVertex2d(lef_x, gd_bottom)
        glVertex2d(rig_x, gd_bottom)
        glVertex2d(rig_x, gd_top)
        glVertex2d(lef_x, gd_bottom)
        glVertex2d(lef_x, gd_top)
        glVertex2d(rig_x, gd_top)
        glEnd()


    def draw_house(self):
        l_wall_x = 130
        r_wall_x = 370
        bot_y = 100
        top_y = 300

        glColor3f(0.8, 0.7, 0.5)
        glBegin(GL_TRIANGLES)
        glVertex2d(l_wall_x, bot_y)
        glVertex2d(l_wall_x, top_y)
        glVertex2d(r_wall_x, top_y)
        glVertex2d(l_wall_x, bot_y)
        glVertex2d(r_wall_x, bot_y)
        glVertex2d(r_wall_x, top_y)

        glEnd()


        glColor3f(0.55, 0.27, 0.07)
        self.trianstruct(l_wall_x, top_y, r_wall_x - l_wall_x, 120)

        do_w = 60
        do_h = 100
        do_l_x = l_wall_x + (r_wall_x - l_wall_x - do_w) / 2
        do_r_x = do_l_x + do_w
        do_b_y = bot_y
        do_t_y = do_b_y + do_h

        glColor3f(0.5, 0.25, 0.0)
        glBegin(GL_TRIANGLES)
        glVertex2d(do_l_x, do_b_y)
        glVertex2d(do_l_x, do_t_y)
        glVertex2d(do_r_x, do_t_y)
        glVertex2d(do_l_x, do_b_y)
        glVertex2d(do_r_x, do_b_y)
        glVertex2d(do_r_x, do_t_y)

        glEnd()


    def setup_projection(self):
        glViewport(0, 0, self.width, self.height)
        glMatrixMode(GL_PROJECTION)
        glLoadIdentity()
        glOrtho(0.0, self.width, 0.0, self.height, 0.0, 1.0)
        glMatrixMode(GL_MODELVIEW)
        glClearColor(0.0, 0.0, 0.0, 1.0)

    def rainfall_overscene(self):
        for i in range(2):
            a = random.uniform(0, self.width)
            b = self.height
            self.drops.append([a, b])

        for dp in self.drops:
            dp[0] += self.initial_ang * 0.3
            dp[1] -= 6
            if dp[0] < 0:
                dp[0] += self.width
            elif dp[0] > self.width:
                dp[0] -= self.width
        new_drops = []
        for dp in self.drops:
            if dp[1] > 0:
                new_drops.append(dp)
        self.drops = new_drops


    def draw_rain(self):
        glColor3f(0.4, 0.7, 1.0)
        glBegin(GL_LINES)
        for a, b in self.drops:
            glVertex2f(a, b)
            glVertex2f(a - self.initial_ang * 2, b - 12)
        glEnd()

    def output_back(self):
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
        glLoadIdentity()
        self.draw_background()
        self.draw_ground()
        self.draw_house()
        self.draw_rain()
        glutSwapBuffers()

    def change_DN(self, value=0):

        if self.condtional_check == 1.0:
            self.initialbgcol += self.trans_speed
        elif self.condtional_check == 0.0:
            self.initialbgcol -= self.trans_speed
        if self.initialbgcol  < 0.0:
            self.initialbgcol = 0.0
        elif self.initialbgcol > 1.0:
            self.initialbgcol = 1.0
        self.rainfall_overscene()
        self.output_back()

    def key_inputboard(self, key, x, y):
        if key == GLUT_KEY_RIGHT:
            self.initial_ang -= 0.3
        elif key == GLUT_KEY_LEFT:
            self.initial_ang += 0.3
        elif key == GLUT_KEY_UP:
            self.condtional_check = 1
        elif key == GLUT_KEY_DOWN:
            self.condtional_check = 0

    def checkrun(self):
        glutInit()
        glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA)
        glutInitWindowSize(self.width, self.height)
        glutInitWindowPosition(200, 200)
        glutCreateWindow(b"House with raining")
        self.setup_projection()
        glutDisplayFunc(self.output_back)
        glutSpecialFunc(self.key_inputboard)
        glutIdleFunc(self.change_DN)
        glutMainLoop()


if __name__ == "__main__":
    scene = House_with_rain()
    scene.checkrun()




#Task2

from OpenGL.GL import *
from OpenGL.GLUT import *
import random

class ball_design:
    def __init__(self, x, y, b_w_half, b_h_half):
        self.x = x
        self.y = y
        self.hx = random.choice([-1, 1])
        self.hy = random.choice([-1, 1])
        self.color = (random.random(), random.random(), random.random())
        self.w_half = b_w_half
        self.h_half = b_h_half


    def move(self, sp):

        self.x += self.hx * sp
        self.y += self.hy * sp
        if self.x >= self.w_half or self.x <= -self.w_half:
            self.hx *= -1
        if self.y >= self.h_half or self.y <= -self.h_half:
            self.hy *= -1



class make_box:
    def __init__(self):
        self.wid = 850
        self.hei = 850
        self.w_half = self.wid / 2
        self.h_half = self.hei / 2
        self.points_cord = []
        self.sp = 3.75
        self.shuttter = 0
        self.shuttter_state = 1
        self.froze_checker = 0
        self.f_cont = 0


        glutInit()
        glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB)
        glutInitWindowSize(self.wid, self.hei)
        glutCreateWindow(b"Amazing Box")

        glClear(GL_COLOR_BUFFER_BIT)
        glMatrixMode(GL_PROJECTION)
        glLoadIdentity()
        glOrtho(-self.w_half, self.h_half, -self.h_half, self.h_half, -1, 1)
        glMatrixMode(GL_MODELVIEW)

        glutDisplayFunc(self.output_back)
        glutIdleFunc(self.anima_part_view)
        glutKeyboardFunc(self.t2_key)
        glutSpecialFunc(self.t1_key)
        glutMouseFunc(self.m1)



    def to_coord(self, x, y):
        return x - (self.wid /2), (self.hei / 2) - y


    def draw_points(self):
        glPointSize(9)
        for a in self.points_cord:
            if self.shuttter and not self.shuttter_state:
                continue
            glColor3f(*a.color)
            glBegin(GL_POINTS)
            glVertex2f(a.x, a.y)
            glEnd()


    def draw_border(self):
        glColor3f(0.7, 0.7, 0.7)
        glBegin(GL_LINES)
        glVertex2f(-self.w_half, -self.h_half)
        glVertex2f(self.w_half, -self.h_half)
        glVertex2f(self.w_half, self.h_half)
        glVertex2f(-self.w_half, self.h_half)
        glEnd()


    def output_back(self):
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
        glLoadIdentity()
        self.draw_border()
        self.draw_points()
        glutSwapBuffers()

    def anima_part_view(self):
        if not self.froze_checker:
            for x in self.points_cord:
                x.move(self.sp)
            if self.shuttter:
                self.f_cont += 1
                if self.f_cont % 50 == 0:
                    self.shuttter_state = 1 - self.shuttter_state
        glutPostRedisplay()


    def m1(self, button, state, a, b):
        if state != GLUT_DOWN:
            return
        if button == GLUT_RIGHT_BUTTON:
            hx, hy = self.to_coord(a, b)
            self.points_cord.append(ball_design(hx, hy, self.w_half, self.h_half))
        elif button == GLUT_LEFT_BUTTON:
            self.shuttter = 1 - self.shuttter

    def t1_key(self, key, a, b):
        if key == GLUT_KEY_UP:
            self.sp *= 1.2
        elif key == GLUT_KEY_DOWN:
            self.sp /= 1.2
            if self.sp < 0.2:
                self.sp = 0.2

    def t2_key(self, key, a, b):
        if key == b' ':
            self.froze_checker = 1 - self.froze_checker
    def run(self):
        glutMainLoop()

if __name__ == "__main__":
    make_box().run()